import { Food } from "./app/shared/models/Food"
import { Tag } from "./app/shared/models/Tag"

export const sample_foods: Food[] = [
  {
    id: '1',
    name: 'Cappuccino',
    cookTime: '5-10',
    price: 5,
    favorite: true,
    origins: ['seattle'],
    stars: 4.8,
    imageUrl: 'https://www.starbucks.in/assets/icon/placeholder.webp',
    tags: ['Coffee', 'Hot'],
  },
  {
    id: '2',
    name: 'Bake In Mushropm Cheese Melt Baguette SW',
    price: 2,
    cookTime: '10-15',
    favorite: true,
    origins: ['us'],
    stars: 4.7,
    imageUrl: 'https://starbucksstatic.cognizantorderserv.com/Items/Large/webP/115301_1.webp',
    tags: ['Snack', 'Bakery'],
  },
  {
    id: '3',
    name: 'Pumpkin Spice Latte',
    price: 6,
    cookTime: '5-10',
    favorite: false,
    origins: ['seattle'],
    stars: 4.5,
    imageUrl: 'https://starbucksstatic.cognizantorderserv.com/Items/Large/webP/102253_1.webp',
    tags: ['Coffee', 'Hot'],
  },
  {
    id: '4',
    name: 'BBQ Chicken Wrap',
    price: 3,
    cookTime: '10-15',
    favorite: true,
    origins: ['us'],
    stars: 4.6,
    imageUrl: 'https://starbucksstatic.cognizantorderserv.com/Items/Large/webP/115299_1.webp',
    tags: ['Snack', 'Bakery'],
  },
  {
    id: '5',
    name: 'Classic Iced Coffee',
    price: 4,
    cookTime: '3-5',
    favorite: false,
    origins: ['italy'],
    stars: 4.2,
    imageUrl: 'https://starbucksstatic.cognizantorderserv.com/Items/Small/115987.png',
    tags: ['Coffee', 'Cold'],
  },
  {
    id: '6',
    name: 'Iced Pumpkin Spice Latte',
    price: 5,
    cookTime: '5-10',
    favorite: true,
    origins: ['seattle'],
    stars: 4.8,
    imageUrl: 'https://starbucksstatic.cognizantorderserv.com/Items/Large/webP/102257_1.webp',
    tags: ['Coffee', 'Cold'],
  },
  {
    id: '7',
    name: 'Iced Saffron Pistachio Latte',
    price: 6,
    cookTime: '5-10',
    favorite: false,
    origins: ['seattle'],
    stars: 4.7,
    imageUrl: 'https://starbucksstatic.cognizantorderserv.com/Items/Large/webP/115768_1.webp',
    tags: ['Coffee', 'Cold'],
  },
  {
    id: '8',
    name: 'Spinach & Corn Sandwich',
    price: 5,
    cookTime: '10-15',
    favorite: true,
    origins: ['france'],
    stars: 4.4,
    imageUrl: 'https://starbucksstatic.cognizantorderserv.com/Items/Large/webP/115583_1.webp',
    tags: ['Snack', 'Bakery'],
  },
]

export const sample_tags: Tag[] = [
  { name: 'All', count: 8 },
  { name: 'Coffee', count: 5 },
  { name: 'Hot', count: 2 },
  { name: 'Cold', count: 3 },
  { name: 'Snack', count: 3 },
  { name: 'Bakery', count: 3 },
]
